name: Deploy
on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Access GitHub Secret
        run: |
          echo "The secret is: ${{ secrets.API_KEY }}"
        env:
          MY_SECRET: ${{ secrets.API_KEY }}
